version: 2
jobs:
  build-code:
    docker:
      - image: node:7.8.0
    steps:
      - checkout

      - run:
          name: echo nodejs information
          command: |
            echo "node version $(node -v) running"
            echo "npm version $(npm -v) running"
            echo "npm registry $(npm config get registry)"

      - run:
          name: install
          command: npm install

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm test

      - run:
          name: notify slack on failure
          when: on_fail
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Turadmin build-publish-deploy false

      - run:
          name: notify slack on sucess
          when: on_success
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Turadmin build-publish-deploy true

  build-image:
    docker:
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
          name: authenticate with gcloud
          command: |
            echo $GCLOUD_DOCKER_PRIVATE_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      # if authentication succeeded - checkout code
      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker

      - run:
          name: build Turadmin docker image and push image to GCR
          command: |
            gcloud auth configure-docker --quiet
            TAG=$(git describe --tags)
            docker build -t turadmin .
            docker tag turadmin eu.gcr.io/dnt-docker-registry-private/turadmin:latest
            docker tag turadmin eu.gcr.io/dnt-docker-registry-private/turadmin:$TAG
            docker push eu.gcr.io/dnt-docker-registry-private/turadmin:latest
            docker push eu.gcr.io/dnt-docker-registry-private/turadmin:$TAG

      - run:
          name: notify slack on sucess
          when: on_success
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Turadmin build-publish-deploy true

      - run:
          name: notify slack on failure
          when: on_fail
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh Turadmin build-publish-deploy false

  deploy-to-dev:
    docker:
      - image: praqma/helmsman:v1.12.0-helm-v2.14.3
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            export IMAGE_TAG=$(git describe --tags)
            helmsman --apply -f .circleci/helmsman-dev-deployment.toml --keep-untracked-releases

  deploy-to-prod:
    docker:
      - image: praqma/helmsman:v1.3.0-helm-v2.8.1
    steps:
      - checkout
      - run:
          name: run helmsman
          command: |
            export IMAGE_TAG=$(git describe --tags)
            helmsman -debug -apply -f .circleci/helmsman-prod-deployment.toml

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-code:
          context: dnt-k8s-dev-beta
      - build-image:
          requires:
            - build-code
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - develop
                - master
      - deploy-to-dev:
          requires:
            - build-image
          context: dnt-k8s-dev-beta
          filters:
            branches:
              only:
                - develop

      - deploy-to-prod:
          requires:
            - build-image
          context: dnt-k8s-prod
          filters:
            branches:
              only:
                - master
