// Generated by CoffeeScript 1.6.3
'use strict';
var fetchAndParse, https, xml2js, restler;

https = require('https');
restler = require('restler');

xml2js = require('xml2js');

fetchAndParse = function (params, cb) {
    var req, url;
    url = "https://ws.geonorge.no/SKWS3Index/ssr/sok?" + params;
    req = https.get(url, function (res) {
        var parser;
        parser = new xml2js.Parser({
            explicitArray: false,
            ignoreAttrs: true
        });
        parser.addListener('end', function (r) {
            return cb(null, r);
        });
        return res.on('data', function (d) {
            return parser.parseString(d);
        });
    });
    return req.on('error', function (e) {
        return cb(e);
    });
};

module.exports = function (search, cb) {
    if (typeof search === 'object') {
        return fetchAndParse(search, cb);
    } else if (typeof search === 'string') {
        return fetchAndParse("navn=" + search + "&epsgKode=4326", cb);
    } else if (typeof search === 'number') {
        return fetchAndParse("ssrId=" + search + "&epsgKode=4326", cb);
    } else {
        return cb(new Error('Unsupported search type'));
    }
};
